<?php
/**
 * @file
 * Custom Module Creation.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function goal_custom_module_help($path, $arg) {
  switch ($path) {
    case "admin/help#goal_custom_module":
      return '' . t("Custom Module Creation") . '';
      break;
  }
} 

function goal_custom_module_menu()
{
    
    $items['goal_custom_module/form'] = array(
        'title' => t('Form'),
        'page callback' => 'goal_custom_module_form_input',
        'access arguments' => array('access content'),
        'file' => 'goal_custom_module.pages.inc',
    );
    $items['goal_custom_module/formall'] = array(
        'title'            => 'All Form',
        'page callback'    => 'goal_custom_module_form_all',
        'access arguments' => array( 'access content' ),
        'file' => 'goal_custom_module.pages.inc',
    );

    return $items;
}

/**
 * Implements hook_block_info().
 */
function goal_custom_module_block_info() {
  $blocks = array();
  $blocks['goal_custom_module'] = array(
    'info' => t('Custom Module'),
  );
  return $blocks;
}

/**
 * Custom content function. 
 * 
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 * 
 * @return 
 *   A result set of the targeted posts.
 */
function goal_custom_module_contents(){
  module_load_include('inc', 'goal_custom_module', 'goal_custom_module.pages');
  return goal_custom_module_form_input();  
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function goal_custom_module_block_view($delta = '') {
    $block = array();
    switch ($delta) {
      case 'goal_custom_module':
        $block['subject'] = '';
        $block['content'] = goal_custom_module_contents();
        break;
    }
    return $block;
}
  
